/*
DML : DATA MODFIFICATION LANGUAGE 


THERE WE HAVE 

INSERT:INSERT USED TO ADD ROWS TO TABLE
UPDATE:UPDATE IS USED TO MODIFY EXISTING STRCUTURE 
DELETE:DELETE IS USED TO DELETE TABLE




*/


-- FOR TEST CASE WE CAN CREATE AND AND PLAY INSERT AND UPDATE DELETE OPTION ON TOP OF TABLE


CREATE TABLE temp_dml1(name varchar(50),age int,address varchar(100));

select * from temp_dml1;




-- now we can play on insert 
